-intstyle "ise" -incremental -o "D:/Users/DAVID/Desktop/davidProcesador/pr4/procesado4/pr4_TB_isim_beh.exe" -prj "D:/Users/DAVID/Desktop/davidProcesador/pr4/procesado4/pr4_TB_beh.prj" "work.pr4_TB" 
